### PR TITLE
(feat): Add request.set_headers and request.prepend_headers

### PR DESCRIPTION
**Pull request by dmmulroy**
This PR adds pluralized versions for `set_header` and `prepend_header` that will each take a list of `#(String, String)` and apply them to the request in the same fashion as the singular versions. In addition, tests have been added to cover the new functions.

### CODE REVIEW

**Comment by lpil** [comment]
Thank you for this, but seeing as one can pipe the existing function I don't yet know of a strong case for their additions.

What was the situation which prompted you to implement these?

**Comment by dmmulroy** [comment]
I like constructing headers in their own function, generally, into a list and adding them to requests as such. Here's an example

```gleam
fn to_http_request(
  client: Client,
  method: Method,
  req: Request,
) -> HttpRequest(String) {
  let headers =
    client
    |> headers
    |> merge_headers(req.headers)

  let body =
    req.body
    |> option.map(json.to_string)
    |> option.unwrap("")

  let query =
    option.map(req.query, fn(params) {
      list.map(params, fn(param) {
        let key = pair.first(param)
        let value = pair.second(param)

        #(uri.percent_encode(key), uri.percent_encode(value))
      })
    })
    |> option.unwrap([])

  request.new()
  |> request.set_method(method)
  |> request_ext.set_headers(headers)
  |> request.set_scheme(Https)
  |> request.set_host(host)
  |> request.set_body(body)
  |> request.set_path(req.path)
  |> request.set_query(query)
}
```

Full code: https://github.com/dmmulroy/glitch/blob/main/src/glitch/api/client.gleam#L97

**Comment by dmmulroy** [comment]
I'd also add there is kind of precedence for this type of API in the library already with `set_query` which takes a list of query params rather than adding one at a time.

```gleam
pub fn set_query(
  req: Request(a),
  query: List(#(String, String)),
) -> Request(a)
```

**Comment by dmmulroy** [comment]
I don't think I'm fully following what you're suggesting here - could you clarify? 

I concur that I definitely don't need the extra `Request` and the `HttpRequest` alias type. I'l probably get rid those tomorrow and just use the `gleam_http` `Request`. That being said, I don't want to expose the `Request` type to users so at _some_ point I need to translate input data to headers. My choices currently are:

1. Repeatedly calling `request.set_header`, but this isn't great because the number of headers I may add is dynamic so its clashes with using a single chain of functions via the pipe operator.

2. Do something like this where I map input data to a gleam_http Request
```gleam
  Request(..request.new(), headers: headers)
  |> request.set_method(method)
  |> request.set_scheme(Https)
  |> request.set_host(host)
  |> request.set_body(body)
  |> request.set_path(req.path)
  |> request.set_query(query)
```

3. Use an "extension module" like `request_ext.set_headers`

**Comment by lpil** [comment]
Let's keep this being something in your codebase for now, and we can see if it's something that there's a demand for later. Time often brings more clarity.

**Comment by dmmulroy** [comment]
Sounds good - thanks for engaging and thanks for your time, always appreciate it.

**Comment by lpil** [comment]
No, thank you!! Contributions are super important

**Comment by dmmulroy** [comment]
See #54 for additional context on why this was closed

**Pull request closed without merging**
