### PR TITLE
Add set_header, and document fixes

### PR DESCRIPTION
**Pull request by adz**

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Fantastic! Thank you very much. Would you mind also updating the change log file for this?

**Comment by adz** [comment]
Sure. Wasn't sure on how you did the change log. Just add a bullet point at the top?

Will address tomorrow.

**Review by lpil — APPROVED** [review]
Perfect! Thank you for being patient as I work through my backlog of pull requests

**Comment by lpil** [comment]
I have released 3.1.0 with this in it. Thanks!

**Pull request merged**
